config/routes.rb
Bookshelf::Application.routes.draw do
  root 'feeds#index'

  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#delete'

  resource :session, only: [:new]

  resources :feeds, only: [:new, :create, :show] do
    resources :entries, only: [:show]
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :feed

  def feed_title
    feed.title
  end
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :entries, dependent: :destroy
  has_many :subscriptions
  has_many :users, through: :subscriptions

  before_create :fetch_feed

  private

  def fetch_feed
    feed = Feedzirra::Feed.fetch_and_parse(url)
    self.title = feed.title.sanitize
    self.etag = feed.etag
    self.last_modified_at = feed.last_modified

    feed.entries.each do |entry|
      entries << Entry.new(
        guid: entry.id,
        url: entry.url,
        title: entry.title.sanitize,
        content: (entry.content || entry.summary).sanitize,
        published_at: entry.published
      )
    end
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :feed
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :email, email: true

  <<<<<<< HEAD
  has_many :subscriptions
  =======
  has_many :subscriptions
  >>>>>>> My commit
  has_many :feeds, through: :subscriptions
  has_many :entries, through: :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize_user

  helper_method :current_user

  def current_user
    @current_user = User.where(username: session[:username]).first
  end

  private

  def authorize_user
    unless User.exists?(username: session[:username])
      redirect_to new_session_path
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def show
    feed = current_user.feeds.find(params[:feed_id])
    @entry = feed.entries.find(params[:id])
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = current_user.feeds
  end

  def show
    @feed = current_user.feeds.find(params[:id])
    @entries = @feed.entries.order(published_at: :desc)
  end

  def new
    @feed = current_user.feeds.new
  end

  def create
    feed = Feed.where(url: params[:feed][:url]).first_or_initialize
    current_user.feeds << feed

    if current_user.feeds.include? feed
      flash[:success] = 'The feed was added!'
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize_user

  def new
  end

  def create
    user = User.find_or_create_by(username: username) do |user|
      user.email = email
    end

    if user.persisted?
      session['username'] = username

      redirect_to root_path
    else
      head 401
    end
  end

  def delete
    session['username'] = nil
    redirect_to root_path
  end

  private

  def username
    env['omniauth.auth']['info']['nickname']
  end

  def email
    env['omniauth.auth']['info']['email']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_feed_menu_item.erb
<li>
  <%= link_to feed.title, feed_path(feed) %>
</li>

app/views/application/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>">
    <span><%= value %></span>
  </div>
<% end %>

<% content_for :javascript do %>
  <script type="text/javascript">
    var flash = $('.flash');

    $(flash).on('click', function(e) {
      flash.hide();
    });
  </script>
<% end %>

app/views/application/_header.erb
<header class="centered-navigation">
  <div class="centered-navigation-wrapper">
    <a href="" class="centered-navigation-menu-button">MENU</a>
    <ul class="centered-navigation-menu">
      <li class="nav-link">
        <%= link_to 'Feeds', root_path %>
      </li>
      <li class="nav-link">
        <%= link_to 'New Feed', new_feed_path %>
      </li>
      <li class="nav-link"><%= link_to 'Sign Out', sign_out_path %></li>
    </ul>
  </div>
</header>

<% content_for :javascript do %>
  <script type="text/javascript">
    var menu = $('.centered-navigation-menu');
    var menuToggle = $('.centered-navigation-menu-button');

    $(menuToggle).on('click', function(e) {
      e.preventDefault();
      menu.slideToggle(function(){
        if(menu.is(':hidden')) {
          menu.removeAttr('style');
        }
      });
    });
  </script>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/application/_sliding_menu.erb
<button type="button" class="js-menu-trigger sliding-menu-button">
  <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/menu.png" alt="Menu Icon">
</button>

<nav class="js-menu sliding-menu-content">
  <ul>
    <%= render partial: 'feed_menu_item', collection: feeds, as: 'feed' %>
  </ul>
</nav>

<div class="js-menu-screen menu-screen"></div>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.js-menu-trigger').on('click touchstart', function(e){
        $('.js-menu').toggleClass('is-visible');
        $('.js-menu-screen').toggleClass('is-visible');
        e.preventDefault();
      });

      $('.js-menu-screen').on('click touchstart', function(e){
        $('.js-menu').toggleClass('is-visible');
        $('.js-menu-screen').toggleClass('is-visible');
        e.preventDefault();
      });
    });
  </script>
<% end %>

app/views/entries/_entry.erb
<%= link_to entry.url, class: 'grid-item', target: :blank do %>
  <h1><%= entry.title %></h1>
<% end %>

app/views/entries/show.erb
<%= render 'sliding_menu', feeds: current_user.feeds %>

<article>
  <p class="type"><%= link_to @entry.feed_title, feed_path(@entry.feed) %></p>
  <h1><%= @entry.title %></h1>
  <p class="date"><%= @entry.published_at.to_date.to_s(:long) %></p>
  <%= raw @entry.content %>
  <!--h2>These override some of the styles specified in the <code>_variables.scss</code> and <code>_typography.scss</code> partials in <a href="//bitters.bourbon.io">Bitters</a>. You can replace the typography variables and the header font specifications in Bitters with these styles. Then you won&rsquo;t need the wrapping class <code>.type-system-name</code>.</h2>
  <p class="date">30 Mar 2014</p>
  <p><span>Lorem ipsum dolor sit amet</span>, consectetur adipisicing elit. Consequatur a, ullam, voluptatum incidunt neque doloremque vel inventore distinctio laudantium harum</a> illo quam nulla dolor alias iure impedit! Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit.
    <a href="javascript:void(0)" class="read-more">Read More <span>&rsaquo;</span></a>
  </p>
  <h3>Subheading lorem</h3>
  <p><span>Consequatur ullam, voluptatum</span> incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit. Accusamus. Consequatur, a, ullam, voluptatum incidunt neque porro numquam doloremque vel inventore distinctio laudantium harum illo quam nulla dolor alias iure impedit! Accusamus.</p-->
  <hr>
  <p class="author"><%= link_to "View Source", @entry.url %></p>
</article>

app/views/feeds/_feed.erb
<%= link_to feed_path(feed), class: 'grid-item' do %>
  <h1><%= feed.title %></h1>
<% end %>

app/views/feeds/index.erb
<% if @feeds.any? %>
  <div class="grid-items-lines">
    <%= render @feeds %>
    <div class="right-cover"></div>
    <div class="bottom-cover"></div>
  </div>
<% else %>
  <div class="empty-grid">
    <%= link_to 'Add your first feed', new_feed_path, class: 'button' %>
  </div>
<% end %>

app/views/feeds/new.erb
<div class="new-feed">
  <%= simple_form_for @feed do |form| %>
    <%= form.input :url, label: 'Feed URL' %>
    <%= form.button :submit, 'Add Feed' %>
  <% end %>
</div>

app/views/feeds/show.erb
<%= render 'sliding_menu', feeds: current_user.feeds %>

<div class="grid-items-lines">
  <%= render @entries %>
  <div class="right-cover"></div>
  <div class="bottom-cover"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title>Bookshelf</title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,400italic,600italic,600,700,700italic,900,300italic,300,200italic,200' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render 'header' if current_user %>
  <div class='body-wrapper'>
    <%= render 'flashes' %>
    <%= yield %>
  </div>
  <%= render 'javascript' %>
</body>
</html>